/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.jiffy.example;

public class Circle extends Shape {
  private transient long swigCPtr;

  protected Circle(long cPtr, boolean cMemoryOwn) {
    super(clazzJNI.Circle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Circle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clazzJNI.delete_Circle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Circle(double r) {
    this(clazzJNI.new_Circle(r), true);
  }

  public double area() {
    return clazzJNI.Circle_area(swigCPtr, this);
  }

  public double perimeter() {
    return clazzJNI.Circle_perimeter(swigCPtr, this);
  }

}
