/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.jiffy.example;

public class converting_java_string_arrays_to_charxx {
  public static int print_args(String[] argv) {
    return converting_java_string_arrays_to_charxxJNI.print_args(argv);
  }

  public static String[] get_args() {
    return converting_java_string_arrays_to_charxxJNI.get_args();
  }

}
