/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.jiffy.example;

public class AddingJavaDowncastsToPolymorphicReturnTypes {
  public static Vehicle vehicle_factory() {
    long cPtr = AddingJavaDowncastsToPolymorphicReturnTypesJNI.vehicle_factory();
    return (cPtr == 0) ? null : new Vehicle(cPtr, false);
  }

}
