/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.jiffy.example;

public class AddingJavaDowncastsToPolymorphicReturnTypesJNI {
  public final static native void Vehicle_start(long jarg1, Vehicle jarg1_);
  public final static native void delete_Vehicle(long jarg1);
  public final static native long new_Ambulance(String jarg1);
  public final static native void Ambulance_start(long jarg1, Ambulance jarg1_);
  public final static native void Ambulance_sound_siren(long jarg1, Ambulance jarg1_);
  public final static native long Ambulance_dynamic_cast(long jarg1, Vehicle jarg1_);
  public final static native void delete_Ambulance(long jarg1);
  public final static native long vehicle_factory();
  public final static native long Ambulance_SWIGUpcast(long jarg1);
}
