/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.jiffy.example;

public class Ambulance extends Vehicle {
  private transient long swigCPtr;

  protected Ambulance(long cPtr, boolean cMemoryOwn) {
    super(AddingJavaDowncastsToPolymorphicReturnTypesJNI.Ambulance_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Ambulance obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AddingJavaDowncastsToPolymorphicReturnTypesJNI.delete_Ambulance(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Ambulance(String volume) {
    this(AddingJavaDowncastsToPolymorphicReturnTypesJNI.new_Ambulance(volume), true);
  }

  public void start() {
    AddingJavaDowncastsToPolymorphicReturnTypesJNI.Ambulance_start(swigCPtr, this);
  }

  public void sound_siren() {
    AddingJavaDowncastsToPolymorphicReturnTypesJNI.Ambulance_sound_siren(swigCPtr, this);
  }

  public static Ambulance dynamic_cast(Vehicle vehicle) {
    long cPtr = AddingJavaDowncastsToPolymorphicReturnTypesJNI.Ambulance_dynamic_cast(Vehicle.getCPtr(vehicle), vehicle);
    return (cPtr == 0) ? null : new Ambulance(cPtr, false);
  }

}
